---
- name: node_exporter | Mkdir path
  file: path={{ item }} state=directory owner=easemob group=easemob
  with_items:
  - /data/apps/opt/node_exporter/bin 
  - /data/apps/var/node_exporter

- name: node_exporter | Copy config file
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
  - {src: /data/apps/opt/exporter/node_exporter, dest: /usr/sbin/node_exporter, owner: root, group: root, mode: 755}

- name: node_exporter | Copy bin file
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
  - {src: start.sh, dest: /data/apps/opt/node_exporter/bin/start.sh, owner: easemob, group: easemob, mode: 755}
  - {src: stop.sh, dest: /data/apps/opt/node_exporter/bin/stop.sh, owner: easemob, group: easemob, mode: 755}
  when: ansible_distribution_major_version == "6" 

- name: node_exporter | Copy systemd service file for centos7
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
  - {src: node_exporter.service, dest: /etc/systemd/system/node_exporter.service, owner: root, group: root, mode: 644}
  - {src: node_exporter.mc, dest: /data/apps/config/monit/node_exporter.mc, owner: easemob, group: easemob, mode: 644}
  when: ansible_distribution_major_version == "7" 

- name: node_exporter | Copy node_exporter.mc for centos6
  template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
  - {src: node_exporter.mc, dest: /data/apps/config/monit/node_exporter.mc, owner: easemob, group: easemob, mode: 644}
  when: ansible_distribution_major_version == "6" 

- name: node_exporter | Copy systemd service file
  template: src=node_exporter dest=/etc/sysconfig/node_exporter owner=root group=root mode=644

- name: node_exporter | Reload node_exporter for centos7
  shell: "sudo systemctl daemon-reload"
  when: ansible_distribution_major_version == "7" 

- name: node_exporter | Restart node_exporter for centos6
  service: name=node_exporter state=restarted enabled=yes
  when: ansible_distribution_major_version == "7" 

- name: node_exporter | Monit reload
  shell: "sudo monit reload"
  when: ansible_distribution_major_version == "6"

- name: node_exporter | start with monit
  shell: "sudo monit restart node_exporter"
  when: ansible_distribution_major_version == "6"
