---
- name: install easemob-all.repo
  template: src=etc/yum.repos.d/easemob-all.repo dest=/etc/yum.repos.d/easemob-all.repo owner=root group=root mode=644


- name: remove some repoes
  file: path={{ item }}  state=absent
  with_items:
    - /etc/yum.repos.d/mysql-community.repo
    - /etc/yum.repos.d/mysql-community-source.repo
    - /etc/yum.repos.d/erlang_solutions.repo


- name: Set yum.conf proxy
  lineinfile: "dest=/etc/yum.conf state=present regexp='^proxy=' line='proxy=http://{{http_proxy_server}}'"
  when: http_proxy_server is defined



- name: yum makecache
  command: /usr/bin/yum makecache
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
