# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180529_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slb',
            name='slb_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slb', to='assets.AssetSlb'),
        ),
    ]
