# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180529_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetslb',
            old_name='slb_id',
            new_name='instanceid',
        ),
        migrations.RenameField(
            model_name='slb',
            old_name='slb_id',
            new_name='instanceid',
        ),
    ]
