# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20180529_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetslb',
            name='cost',
            field=models.ManyToManyField(default='', null=True, related_name='slbcost', to='assets.Slb'),
        ),
    ]
