# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetslb_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slb',
            name='instanceid',
            field=models.CharField(max_length=64),
        ),
    ]
