# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180529_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetslb',
            name='cost',
        ),
        migrations.AddField(
            model_name='slb',
            name='slbinfo',
            field=models.ManyToManyField(default='', null=True, related_name='slbinfo', to='assets.AssetSlb'),
        ),
    ]
