# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20180529_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slb',
            name='slbinfo',
        ),
        migrations.AddField(
            model_name='slb',
            name='slbnode',
            field=models.ManyToManyField(default='', null=True, related_name='slbnode', to='assets.NodeSlb'),
        ),
    ]
