# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20180530_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slb',
            name='slbnode',
        ),
        migrations.AddField(
            model_name='slb',
            name='slbinfo',
            field=models.ManyToManyField(default='', null=True, related_name='slbinfo', to='assets.AssetSlb'),
        ),
    ]
