# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20180530_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='instanceId',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='ecs',
            name='ecsinfo',
            field=models.ManyToManyField(default='', null=True, related_name='ecsinfo', to='assets.Asset'),
        ),
    ]
