# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20180530_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='InstanceNetworkType',
            field=models.CharField(default='', max_length=128),
        ),
    ]
