# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_instancenetworktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetslb',
            name='slb_status',
        ),
        migrations.AddField(
            model_name='assetslb',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
