---
#- name: Install the monit packages
#  yum: name={{ item }} state=latest
#  with_items: packages

- name: Put the init files
  template: src=etc/init.d/monit dest=/etc/init.d/monit owner=root group=root mode=755

- name: Install the monit file
  synchronize: src=/usr/bin/monit dest=/usr/bin/ rsync_opts="-avz"


- name: Put the files /etc/sysconfig/monit
  template: src=etc/sysconfig/monit dest=/etc/sysconfig/monit owner=root group=root mode=500

- name: Load /etc/sysconfig/monit when start
  lineinfile: "dest=/etc/init.d/monit state=present regexp='^. /etc/init.d/functions' line='. /etc/init.d/functions; . /etc/sysconfig/monit'"
#  when: ansible_distribution == 'CentOS' and ansible_lsb.major_release|int < 7

- name: Ensure monit config directory exists
  file: path={{ item }} state=directory owner=easemob group=easemob
  with_items:
    - /data/apps/config/monit
    - /data/apps/log/monit/

- name: Put the files to /data/apps/config/monit
  template: src=data/apps/config/monit/{{ item }} dest=/data/apps/config/monit/{{ item }} owner=easemob group=easemob mode=750
  with_items:
     - disk.mc
     - sshd.mc
     - cron.mc
     - file.mc
     - system.mc
  notify:
     - reload monit

- name: Put the files /etc/monitrc
  template: src=etc/monitrc dest=/etc/monitrc owner=root group=root mode=700
  notify:
     - reload monit

- name: start and enable monit
  service: name=monit state=started enabled=yes
