# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=128)),
                ('cmd', models.CharField(max_length=128)),
                ('hosts', models.TextField(blank=True, null=True)),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('timedelta', models.FloatField(default=0.0, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomTasks',
        ),
        migrations.DeleteModel(
            name='RuncmdHistory',
        ),
    ]
